Script 1: Main

In [1]:
import numpy as np

In [2]:
def randomization(n):
    """
    Arg:
      n - an integer
    Returns:
      A - a randomly-generated nx1 Numpy array.
    """
    A = np.random.rand(n,1)
    return A


In [3]:
randomization(4)

array([[0.6920454 ],
       [0.70568758],
       [0.10268958],
       [0.55999863]])

In [4]:
def operations(h, w):
    """
    Takes two inputs, h and w, and makes two Numpy arrays A and B of size
    h x w, and returns A, B, and s, the sum of A and B.

    Arg:
      h - an integer describing the height of A and B
      w - an integer describing the width of A and B
    Returns (in this order):
      A - a randomly-generated h x w Numpy array.
      B - a randomly-generated h x w Numpy array.
      s - the sum of A and B.
    """
    A = np.random.rand(h,w)
    B = np.random.rand(h,w)
    s = A + B
    return A, B, s

In [16]:
operations(3,4)

(array([[0.75858878, 0.84046735, 0.06701002, 0.00564776],
        [0.84779603, 0.39300166, 0.25718968, 0.55184317],
        [0.46896085, 0.0038267 , 0.62576289, 0.68885226]]),
 array([[0.57740583, 0.5472059 , 0.24129197, 0.34236439],
        [0.73386251, 0.75614121, 0.65791052, 0.54805684],
        [0.70269002, 0.6030043 , 0.47035474, 0.07914916]]),
 array([[1.33599461, 1.38767324, 0.30830198, 0.34801215],
        [1.58165854, 1.14914287, 0.91510019, 1.09990001],
        [1.17165087, 0.606831  , 1.09611762, 0.76800142]]))

In [5]:
def norm(A, B):
    """
    Takes two Numpy column arrays, A and B, and returns the L2 norm of their
    sum.

    Arg:
      A - a Numpy array
      B - a Numpy array
    Returns:
      s - the L2 norm of A+B.
    """
    s = np.linalg.norm(A+B)
    return s

In [18]:
norm(np.array([1,2,3]), np.array([4,5,6]))

12.449899597988733

In [6]:

def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    out = np.tanh(np.matmul(weights.T, inputs))
    return out

In [7]:
neural_network(np.array([1,2]), np.array([3,4]))

0.9999999994421064

In [8]:

def scalar_function(x, y):
    """
    Returns the f(x,y) defined in the problem statement.
    """
    result = x*y if x<=y else x/y
    return result

In [9]:
print(scalar_function(3,2))
print(scalar_function(2,3))

1.5
6


In [10]:
def vector_function(x, y):
    """
    Make sure vector_function can deal with vector input x,y 
    """
    vector_function = np.vectorize(scalar_function)
    return vector_function(x, y)

In [11]:
vector_function(np.array([3,2]), np.array([2,3]))

array([1.5, 6. ])

Script 2: Debug

In [14]:
import pdb

In [49]:
def get_sum_metrics(predictions, metrics=None):
    
    if metrics is None:
        metrics = []

    for i in range(3):
        metrics.append(lambda x, i=i: x + i)

    sum_metrics = 0
    for metric in metrics:
        sum_metrics += metric(predictions)
    
    return sum_metrics

In [50]:
def main():
    print(get_sum_metrics(0))  # Should be (0 + 0) + (0 + 1) + (0 + 2) = 3
    print(get_sum_metrics(1))  # Should be (1 + 0) + (1 + 1) + (1 + 2) = 6
    print(get_sum_metrics(2))  # Should be (2 + 0) + (2 + 1) + (2 + 2) = 9
    print(get_sum_metrics(3, [lambda x: x]))  # Should be (3) + (3 + 0) + (3 + 1) + (3 + 2) = 15
    print(get_sum_metrics(0))  # Should be (0 + 0) + (0 + 1) + (0 + 2) = 3
    print(get_sum_metrics(1))  # Should be (1 + 0) + (1 + 1) + (1 + 2) = 6
    print(get_sum_metrics(2))  # Should be (2 + 0) + (2 + 1) + (2 + 2) = 9

if __name__ == "__main__":
    main()


3
6
9
15
3
6
9
